package bunny.lib.utils;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.particle.ParticleTypes;
import net.minecraft.particle.SimpleParticleType;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public final class ItemManager {

    public static final Set<Item> ENCHANTABLE = new HashSet<>();
    static {
        ENCHANTABLE.add(Items.SHEARS);
        ENCHANTABLE.add(Items.FLINT_AND_STEEL);
        ENCHANTABLE.add(Items.SHIELD);
    }

    public static final Set<Item> HEAD_EQUIPPABLE_ITEMS = new HashSet<>();
    static {
        // Glass
        HEAD_EQUIPPABLE_ITEMS.add(Items.GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.TINTED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.WHITE_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.ORANGE_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.MAGENTA_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.LIGHT_BLUE_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.YELLOW_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.LIME_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.PINK_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.GRAY_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.LIGHT_GRAY_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.CYAN_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.PURPLE_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.BLUE_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.BROWN_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.GREEN_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.RED_STAINED_GLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.BLACK_STAINED_GLASS);

        // Fence Gates
        HEAD_EQUIPPABLE_ITEMS.add(Items.OAK_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.SPRUCE_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.BIRCH_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.JUNGLE_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.ACACIA_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.DARK_OAK_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.MANGROVE_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.CHERRY_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.BAMBOO_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.CRIMSON_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.WARPED_FENCE_GATE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.PALE_OAK_FENCE_GATE);

        // Banners
        HEAD_EQUIPPABLE_ITEMS.add(Items.WHITE_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.ORANGE_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.MAGENTA_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.LIGHT_BLUE_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.YELLOW_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.LIME_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.PINK_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.GRAY_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.LIGHT_GRAY_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.CYAN_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.PURPLE_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.BLUE_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.BROWN_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.GREEN_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.RED_BANNER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.BLACK_BANNER);

        // Misc
        HEAD_EQUIPPABLE_ITEMS.add(Items.END_ROD);
        HEAD_EQUIPPABLE_ITEMS.add(Items.SPYGLASS);
        HEAD_EQUIPPABLE_ITEMS.add(Items.BONE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.LEAD);
        HEAD_EQUIPPABLE_ITEMS.add(Items.COD);
        HEAD_EQUIPPABLE_ITEMS.add(Items.LIGHTNING_ROD);
        HEAD_EQUIPPABLE_ITEMS.add(Items.FEATHER);

        HEAD_EQUIPPABLE_ITEMS.add(Items.AZALEA);
        HEAD_EQUIPPABLE_ITEMS.add(Items.FLOWERING_AZALEA);
        HEAD_EQUIPPABLE_ITEMS.add(Items.OBSERVER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.POINTED_DRIPSTONE);
        HEAD_EQUIPPABLE_ITEMS.add(Items.STONECUTTER);
        HEAD_EQUIPPABLE_ITEMS.add(Items.SCAFFOLDING);
        HEAD_EQUIPPABLE_ITEMS.add(Items.LECTERN);
    }

    public static final Map<Item, Integer> MAX_STACK_OVERRIDES = new HashMap<>();
    static {
        // 64
        MAX_STACK_OVERRIDES.put(Items.SNOWBALL, 64);
        MAX_STACK_OVERRIDES.put(Items.ENDER_PEARL, 64);
        MAX_STACK_OVERRIDES.put(Items.EGG, 64);
        MAX_STACK_OVERRIDES.put(Items.HONEY_BOTTLE, 64);
        MAX_STACK_OVERRIDES.put(Items.ARMOR_STAND, 64);

        MAX_STACK_OVERRIDES.put(Items.WHITE_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.ORANGE_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.MAGENTA_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_BLUE_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.YELLOW_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.LIME_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.PINK_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.GRAY_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_GRAY_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.CYAN_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.PURPLE_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.BLUE_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.BROWN_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.GREEN_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.RED_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.BLACK_BANNER, 64);

        MAX_STACK_OVERRIDES.put(Items.OAK_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.SPRUCE_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.BIRCH_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.JUNGLE_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.ACACIA_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.DARK_OAK_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.MANGROVE_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.CHERRY_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.BAMBOO_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.CRIMSON_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.WARPED_SIGN, 64);

        MAX_STACK_OVERRIDES.put(Items.OAK_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.SPRUCE_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.BIRCH_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.JUNGLE_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.ACACIA_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.DARK_OAK_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.MANGROVE_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.CHERRY_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.BAMBOO_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.CRIMSON_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.WARPED_HANGING_SIGN, 64);

        // 16
        MAX_STACK_OVERRIDES.put(Items.MUSHROOM_STEW, 16);
        MAX_STACK_OVERRIDES.put(Items.BEETROOT_SOUP, 16);
        MAX_STACK_OVERRIDES.put(Items.RABBIT_STEW, 16);

        MAX_STACK_OVERRIDES.put(Items.SNIFFER_EGG, 16);

        MAX_STACK_OVERRIDES.put(Items.SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.WHITE_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.ORANGE_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.MAGENTA_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_BLUE_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.YELLOW_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.LIME_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.PINK_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.GRAY_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_GRAY_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.CYAN_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.PURPLE_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.BLUE_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.BROWN_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.GREEN_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.RED_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.BLACK_SHULKER_BOX, 16);

        MAX_STACK_OVERRIDES.put(Items.WHITE_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.ORANGE_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.MAGENTA_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_BLUE_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.YELLOW_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.LIME_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.PINK_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.GRAY_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_GRAY_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.CYAN_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.PURPLE_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.BLUE_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.BROWN_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.GREEN_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.RED_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.BLACK_BED, 16);

        MAX_STACK_OVERRIDES.put(Items.MINECART, 16);
        MAX_STACK_OVERRIDES.put(Items.CHEST_MINECART, 16);
        MAX_STACK_OVERRIDES.put(Items.FURNACE_MINECART, 16);
        MAX_STACK_OVERRIDES.put(Items.TNT_MINECART, 16);
        MAX_STACK_OVERRIDES.put(Items.HOPPER_MINECART, 16);
        MAX_STACK_OVERRIDES.put(Items.COMMAND_BLOCK_MINECART, 16);

        // 1
        MAX_STACK_OVERRIDES.put(Items.DRAGON_EGG, 1);
    }

    public static final Map<Item, SimpleParticleType> SHERD_PARTICLE = new HashMap<>();
    static {
        SHERD_PARTICLE.put(Items.ANGLER_POTTERY_SHERD, ParticleTypes.BUBBLE);
        SHERD_PARTICLE.put(Items.ARCHER_POTTERY_SHERD, ParticleTypes.CRIT);
        SHERD_PARTICLE.put(Items.ARMS_UP_POTTERY_SHERD, ParticleTypes.TOTEM_OF_UNDYING);
        SHERD_PARTICLE.put(Items.BLADE_POTTERY_SHERD, ParticleTypes.SWEEP_ATTACK);
        SHERD_PARTICLE.put(Items.BREWER_POTTERY_SHERD, ParticleTypes.EFFECT);
        SHERD_PARTICLE.put(Items.BURN_POTTERY_SHERD, ParticleTypes.FLAME);
        SHERD_PARTICLE.put(Items.DANGER_POTTERY_SHERD, ParticleTypes.LARGE_SMOKE);
        SHERD_PARTICLE.put(Items.EXPLORER_POTTERY_SHERD, ParticleTypes.ENCHANT);
        SHERD_PARTICLE.put(Items.FLOW_POTTERY_SHERD, ParticleTypes.SPLASH);
        SHERD_PARTICLE.put(Items.FRIEND_POTTERY_SHERD, ParticleTypes.HEART);
        SHERD_PARTICLE.put(Items.GUSTER_POTTERY_SHERD, ParticleTypes.CLOUD);
        SHERD_PARTICLE.put(Items.HEART_POTTERY_SHERD, ParticleTypes.HEART);
        SHERD_PARTICLE.put(Items.HEARTBREAK_POTTERY_SHERD, ParticleTypes.DAMAGE_INDICATOR);
        SHERD_PARTICLE.put(Items.HOWL_POTTERY_SHERD, ParticleTypes.SOUL);
        SHERD_PARTICLE.put(Items.MINER_POTTERY_SHERD, ParticleTypes.CRIT);
        SHERD_PARTICLE.put(Items.MOURNER_POTTERY_SHERD, ParticleTypes.SOUL_FIRE_FLAME);
        SHERD_PARTICLE.put(Items.PLENTY_POTTERY_SHERD, ParticleTypes.HAPPY_VILLAGER);
        SHERD_PARTICLE.put(Items.PRIZE_POTTERY_SHERD, ParticleTypes.FIREWORK);
        SHERD_PARTICLE.put(Items.SCRAPE_POTTERY_SHERD, ParticleTypes.ASH);
        SHERD_PARTICLE.put(Items.SHEAF_POTTERY_SHERD, ParticleTypes.COMPOSTER);
        SHERD_PARTICLE.put(Items.SHELTER_POTTERY_SHERD, ParticleTypes.ENCHANT);
        SHERD_PARTICLE.put(Items.SKULL_POTTERY_SHERD, ParticleTypes.SMOKE);
        SHERD_PARTICLE.put(Items.SNORT_POTTERY_SHERD, ParticleTypes.POOF);
    }

    public static final Set<Item> SHERDS = new HashSet<>();
    static {
        SHERDS.add(Items.ANGLER_POTTERY_SHERD);
        SHERDS.add(Items.ARCHER_POTTERY_SHERD);
        SHERDS.add(Items.ARMS_UP_POTTERY_SHERD);
        SHERDS.add(Items.BLADE_POTTERY_SHERD);
        SHERDS.add(Items.BREWER_POTTERY_SHERD);
        SHERDS.add(Items.BURN_POTTERY_SHERD);
        SHERDS.add(Items.DANGER_POTTERY_SHERD);
        SHERDS.add(Items.EXPLORER_POTTERY_SHERD);
        SHERDS.add(Items.FLOW_POTTERY_SHERD);
        SHERDS.add(Items.FRIEND_POTTERY_SHERD);
        SHERDS.add(Items.GUSTER_POTTERY_SHERD);
        SHERDS.add(Items.HEART_POTTERY_SHERD);
        SHERDS.add(Items.HEARTBREAK_POTTERY_SHERD);
        SHERDS.add(Items.HOWL_POTTERY_SHERD);
        SHERDS.add(Items.MINER_POTTERY_SHERD);
        SHERDS.add(Items.MOURNER_POTTERY_SHERD);
        SHERDS.add(Items.PLENTY_POTTERY_SHERD);
        SHERDS.add(Items.PRIZE_POTTERY_SHERD);
        SHERDS.add(Items.SCRAPE_POTTERY_SHERD);
        SHERDS.add(Items.SHEAF_POTTERY_SHERD);
        SHERDS.add(Items.SHELTER_POTTERY_SHERD);
        SHERDS.add(Items.SKULL_POTTERY_SHERD);
        SHERDS.add(Items.SNORT_POTTERY_SHERD);
    }

    public static final Set<Block> BRICK_BREAKABLE_GLASS_BLOCKS = new HashSet<>(Set.of(
            Blocks.GLASS,
            Blocks.WHITE_STAINED_GLASS,
            Blocks.ORANGE_STAINED_GLASS,
            Blocks.MAGENTA_STAINED_GLASS,
            Blocks.LIGHT_BLUE_STAINED_GLASS,
            Blocks.YELLOW_STAINED_GLASS,
            Blocks.LIME_STAINED_GLASS,
            Blocks.PINK_STAINED_GLASS,
            Blocks.GRAY_STAINED_GLASS,
            Blocks.LIGHT_GRAY_STAINED_GLASS,
            Blocks.CYAN_STAINED_GLASS,
            Blocks.PURPLE_STAINED_GLASS,
            Blocks.BLUE_STAINED_GLASS,
            Blocks.BROWN_STAINED_GLASS,
            Blocks.GREEN_STAINED_GLASS,
            Blocks.RED_STAINED_GLASS,
            Blocks.BLACK_STAINED_GLASS,

            Blocks.GLASS_PANE,
            Blocks.WHITE_STAINED_GLASS_PANE,
            Blocks.ORANGE_STAINED_GLASS_PANE,
            Blocks.MAGENTA_STAINED_GLASS_PANE,
            Blocks.LIGHT_BLUE_STAINED_GLASS_PANE,
            Blocks.YELLOW_STAINED_GLASS_PANE,
            Blocks.LIME_STAINED_GLASS_PANE,
            Blocks.PINK_STAINED_GLASS_PANE,
            Blocks.GRAY_STAINED_GLASS_PANE,
            Blocks.LIGHT_GRAY_STAINED_GLASS_PANE,
            Blocks.CYAN_STAINED_GLASS_PANE,
            Blocks.PURPLE_STAINED_GLASS_PANE,
            Blocks.BLUE_STAINED_GLASS_PANE,
            Blocks.BROWN_STAINED_GLASS_PANE,
            Blocks.GREEN_STAINED_GLASS_PANE,
            Blocks.RED_STAINED_GLASS_PANE,
            Blocks.BLACK_STAINED_GLASS_PANE
    ));

    public static final Set<Block> BRICK_BREAKABLE_GLASS_AND_TINTED_BLOCKS = new HashSet<>();
    static {
        BRICK_BREAKABLE_GLASS_AND_TINTED_BLOCKS.addAll(BRICK_BREAKABLE_GLASS_BLOCKS);
        BRICK_BREAKABLE_GLASS_AND_TINTED_BLOCKS.add(Blocks.TINTED_GLASS);
    }

    private ItemManager() {}
}
