package net.louis.overhaulmod.utils;

import net.minecraft.item.Item;
import net.minecraft.item.Items;

import java.util.HashMap;
import java.util.Map;

public final class StackSizeManager {

    public static final Map<Item, Integer> MAX_STACK_OVERRIDES = new HashMap<>();

    static {
        // 64
        MAX_STACK_OVERRIDES.put(Items.SNOWBALL, 64);
        MAX_STACK_OVERRIDES.put(Items.ENDER_PEARL, 64);
        MAX_STACK_OVERRIDES.put(Items.EGG, 64);
        MAX_STACK_OVERRIDES.put(Items.HONEY_BOTTLE, 64);
        MAX_STACK_OVERRIDES.put(Items.ARMOR_STAND, 64);

        MAX_STACK_OVERRIDES.put(Items.WHITE_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.ORANGE_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.MAGENTA_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_BLUE_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.YELLOW_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.LIME_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.PINK_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.GRAY_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_GRAY_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.CYAN_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.PURPLE_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.BLUE_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.BROWN_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.GREEN_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.RED_BANNER, 64);
        MAX_STACK_OVERRIDES.put(Items.BLACK_BANNER, 64);

        MAX_STACK_OVERRIDES.put(Items.OAK_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.SPRUCE_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.BIRCH_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.JUNGLE_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.ACACIA_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.DARK_OAK_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.MANGROVE_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.CHERRY_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.BAMBOO_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.CRIMSON_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.WARPED_SIGN, 64);

        MAX_STACK_OVERRIDES.put(Items.OAK_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.SPRUCE_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.BIRCH_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.JUNGLE_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.ACACIA_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.DARK_OAK_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.MANGROVE_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.CHERRY_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.BAMBOO_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.CRIMSON_HANGING_SIGN, 64);
        MAX_STACK_OVERRIDES.put(Items.WARPED_HANGING_SIGN, 64);

        // 16
        MAX_STACK_OVERRIDES.put(Items.MUSHROOM_STEW, 16);
        MAX_STACK_OVERRIDES.put(Items.BEETROOT_SOUP, 16);
        MAX_STACK_OVERRIDES.put(Items.RABBIT_STEW, 16);

        MAX_STACK_OVERRIDES.put(Items.SNIFFER_EGG, 16);

        MAX_STACK_OVERRIDES.put(Items.SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.WHITE_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.ORANGE_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.MAGENTA_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_BLUE_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.YELLOW_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.LIME_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.PINK_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.GRAY_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_GRAY_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.CYAN_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.PURPLE_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.BLUE_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.BROWN_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.GREEN_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.RED_SHULKER_BOX, 16);
        MAX_STACK_OVERRIDES.put(Items.BLACK_SHULKER_BOX, 16);

        MAX_STACK_OVERRIDES.put(Items.WHITE_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.ORANGE_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.MAGENTA_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_BLUE_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.YELLOW_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.LIME_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.PINK_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.GRAY_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.LIGHT_GRAY_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.CYAN_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.PURPLE_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.BLUE_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.BROWN_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.GREEN_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.RED_BED, 16);
        MAX_STACK_OVERRIDES.put(Items.BLACK_BED, 16);

        MAX_STACK_OVERRIDES.put(Items.MINECART, 16);
        MAX_STACK_OVERRIDES.put(Items.CHEST_MINECART, 16);
        MAX_STACK_OVERRIDES.put(Items.FURNACE_MINECART, 16);
        MAX_STACK_OVERRIDES.put(Items.TNT_MINECART, 16);
        MAX_STACK_OVERRIDES.put(Items.HOPPER_MINECART, 16);
        MAX_STACK_OVERRIDES.put(Items.COMMAND_BLOCK_MINECART, 16);

        // 1
        MAX_STACK_OVERRIDES.put(Items.DRAGON_EGG, 1);
    }


    private StackSizeManager() {}
}
